### ISSUE TITLE
"!" tag on data-if-username does not work

### ISSUE THREAD

**Issue by DainPLay** [Fandom-zh/Gadget-UserFunctions#1]
It seems it doesn't work as intended. "!" tag gets ignored.
It even displays its functionaluity wrongly on the main page https://dev.fandom.com/wiki/UserFunctions

**Comment by dragon-fish** [comment]
Looks like I have to deal with these shitty codes I wrote years ago. I'll try but no promise.

**Comment by DainPLay** [comment]
Much thanks man!
